### ISSUE TITLE
README update for sudo requirements

### ISSUE THREAD

**Issue by infamousjoeg** [quincycheng/cicd#1]
I believe it is important to note the `root` privileges necessary to properly run [bin/start.sh](bin/start.sh).

I needed to run `sudo ./bin/start.sh` in order to have it orchestrate with proper escalated privileges.

**Comment by infamousjoeg** [comment]
Actually, `sudo ./bin/start.sh` lead to errors on my `jgarcia` user being used instead of `root`... so that won't work.

This will need to be run as the `root` user only.

**Comment by quincycheng** [comment]
Good point.   There are many installation and update actions that requires privileges.    Let me update README

**Comment by quincycheng** [comment]
README updated
